//! Declares the app's commands to Tauri and generates the main window's capability file.
//!
//! Tauri creates an `allow-<command>` permission for each command listed here; the UI can call
//! only what capabilities/default.json grants (deny by default). The capability file is written
//! from this same list, so the two can never drift apart. Keep in sync with lib.rs.

const COMMANDS: &[&str] = &[
    "get_app_status",
    "complete_setup",
    "login",
    "logout",
    "lock_screen",
    "unlock_with_pin",
    "unlock_with_password",
    "heartbeat",
    "change_own_password",
    "set_own_pin",
    "list_users",
    "create_user",
    "update_user",
    "reset_user_password",
    "get_clinic_settings",
    "update_clinic_settings",
    "list_audit",
    "list_categories",
    "save_category",
    "list_suppliers",
    "save_supplier",
    "list_products",
    "get_product",
    "save_product",
    "stock_in",
    "adjust_stock",
    "list_stock_ledger",
    "list_expiring",
    "search_products_for_sale",
    "recent_products_for_sale",
    "search_clients",
    "save_client",
    "get_client_profile",
    "check_client_duplicates",
    "find_duplicate_clients",
    "merge_clients",
    "list_services",
    "save_service",
    "quote_bill",
    "finalize_bill",
    "list_bills",
    "get_bill",
    "cancel_bill",
    "return_bill_items",
    "correct_bill",
    "get_receipt",
    "export_receipt_pdf",
    "open_export",
    "open_whatsapp",
    "get_dashboard",
    "sales_report",
    "product_sales_report",
    "stock_report",
    "get_system_info",
    "get_health",
    "list_backups",
    "create_backup",
    "restore_backup",
    "open_folder",
];

fn write_capability() {
    let permissions: Vec<String> = std::iter::once("\"core:default\"".to_string())
        .chain(COMMANDS.iter().map(|c| format!("\"allow-{}\"", c.replace('_', "-"))))
        .collect();
    let json = format!(
        "{{\n  \"$schema\": \"../gen/schemas/desktop-schema.json\",\n  \"identifier\": \"main-window\",\n  \
         \"description\": \"What the main window's UI may call. Generated by build.rs from COMMANDS; do not edit.\",\n  \
         \"windows\": [\"main\"],\n  \"permissions\": [\n    {}\n  ]\n}}\n",
        permissions.join(",\n    ")
    );
    let path = std::path::Path::new("capabilities").join("default.json");
    // Only write when it changed, so Tauri's file watcher does not rebuild in a loop.
    if std::fs::read_to_string(&path).ok().as_deref() != Some(json.as_str()) {
        if let Err(error) = std::fs::write(&path, json) {
            panic!("could not write {}: {error}", path.display());
        }
    }
}

fn main() {
    write_capability();
    let attributes = tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(COMMANDS));
    if let Err(error) = tauri_build::try_build(attributes) {
        panic!("tauri-build failed: {error:#}");
    }
}
