#!/usr/bin/env node
// Offline project dependencies for SkinDocJyotsna (works on Windows and macOS).
//
//   node scripts/offline-deps.mjs vendor  <dir>   (machine WITH internet) copy every npm package and
//                                                 Rust crate the project needs into <dir>
//   node scripts/offline-deps.mjs restore <dir>   (offline machine) install npm packages from <dir> and
//                                                 point cargo at the vendored crates
//   node scripts/offline-deps.mjs online          undo "restore" for cargo (use crates.io again)
//
// <dir> is normally <offline bundle>/project-deps. npm packages are cached for ALL platforms
// (Windows x64, macOS arm64, macOS x64), so one vendored folder builds on any of them.

import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fail, isWindows, log, probe, repoRoot, run, warn } from './lib/run.mjs';

const cargoConfigPath = join(repoRoot, '.cargo', 'config.toml');
const GENERATED_MARKER = '# Generated by scripts/offline-deps.mjs';

// The Tauri bundler downloads its Windows installer tools (NSIS + plugins) into this folder
// on the first `tauri build`. Copying it makes later .exe builds work without internet.
const tauriToolsCache = isWindows && process.env.LOCALAPPDATA ? join(process.env.LOCALAPPDATA, 'tauri') : null;

// Only the platforms the app is built on: Windows x64, macOS Apple Silicon and Intel.
const BUILD_OS = ['win32', 'darwin'];
const BUILD_CPU = ['x64', 'arm64'];

function neededOnBuildPlatforms(entry) {
  const osOk = !entry.os || entry.os.some((os) => BUILD_OS.includes(os));
  const cpuOk = !entry.cpu || entry.cpu.some((cpu) => BUILD_CPU.includes(cpu));
  return osOk && cpuOk;
}

/** Every package tarball URL in package-lock.json, including other build platforms' optional packages. */
function lockfileTarballs() {
  const lockPath = join(repoRoot, 'package-lock.json');
  if (!existsSync(lockPath)) fail('package-lock.json not found. Run "npm install" once with internet first.');
  const lock = JSON.parse(readFileSync(lockPath, 'utf8'));
  const urls = new Set();
  for (const [key, entry] of Object.entries(lock.packages ?? {})) {
    if (key === '' || entry.link || !entry.resolved || !neededOnBuildPlatforms(entry)) continue;
    if (!entry.resolved.startsWith('https://')) fail(`Unexpected non-HTTPS package source: ${entry.resolved}`);
    urls.add(entry.resolved);
  }
  return [...urls].sort();
}

function vendor(targetDir) {
  const out = resolve(targetDir);
  const npmCache = join(out, 'npm-cache');
  mkdirSync(npmCache, { recursive: true });

  const urls = lockfileTarballs();
  log(`Caching ${urls.length} npm packages (all platforms) into ${npmCache}`);
  const batchSize = 40;
  for (let i = 0; i < urls.length; i += batchSize) {
    run('npm', ['cache', 'add', '--cache', npmCache, ...urls.slice(i, i + batchSize)]);
    console.log(`    ${Math.min(i + batchSize, urls.length)}/${urls.length}`);
  }
  run('npm', ['cache', 'verify', '--cache', npmCache]);
  copyFileSync(join(repoRoot, 'package-lock.json'), join(out, 'package-lock.json'));

  const hasCargo = probe('cargo') !== null;
  if (hasCargo) {
    const cargoVendor = join(out, 'cargo-vendor');
    log(`Vendoring Rust crates into ${cargoVendor}`);
    if (!existsSync(join(repoRoot, 'Cargo.lock'))) run('cargo', ['generate-lockfile']);
    run('cargo', ['vendor', '--locked', '--versioned-dirs', cargoVendor], { capture: true });
    copyFileSync(join(repoRoot, 'Cargo.lock'), join(out, 'Cargo.lock'));
  } else {
    warn('cargo not found: Rust crates were NOT vendored. Re-run on a machine with Rust installed.');
  }

  let tauriTools = false;
  if (tauriToolsCache && existsSync(tauriToolsCache)) {
    log(`Copying Tauri installer tools (NSIS) from ${tauriToolsCache}`);
    cpSync(tauriToolsCache, join(out, 'tauri-tools-windows'), { recursive: true });
    tauriTools = true;
  } else if (isWindows) {
    warn('Tauri installer tools not cached yet: run one "npm run build" with internet, then vendor again.');
  }

  writeFileSync(
    join(out, 'manifest.txt'),
    [`CREATED_UTC=${new Date().toISOString()}`, `NPM_PACKAGES=${urls.length}`, `CARGO_VENDORED=${hasCargo}`, `TAURI_TOOLS_WINDOWS=${tauriTools}`].join('\n') + '\n',
  );
  log(`Done: ${out}`);
}

function restore(sourceDir) {
  const src = resolve(sourceDir);
  const npmCache = join(src, 'npm-cache');
  if (!existsSync(npmCache)) fail(`No npm-cache folder in ${src}`);

  log('Installing npm packages from the offline cache');
  run('npm', ['ci', '--offline', '--no-audit', '--no-fund', '--cache', npmCache]);

  const cargoVendor = join(src, 'cargo-vendor');
  if (existsSync(cargoVendor)) {
    log(`Pointing cargo at vendored crates: ${cargoVendor}`);
    mkdirSync(dirname(cargoConfigPath), { recursive: true });
    const vendorPath = cargoVendor.replaceAll('\\', '/');
    writeFileSync(
      cargoConfigPath,
      [
        `${GENERATED_MARKER} - machine-specific, do not commit. Undo with: node scripts/offline-deps.mjs online`,
        '[source.crates-io]',
        'replace-with = "vendored-sources"',
        '',
        '[source.vendored-sources]',
        `directory = "${vendorPath}"`,
        '',
        '[net]',
        'offline = true',
        '',
      ].join('\n'),
    );
  } else {
    warn('No cargo-vendor folder: Rust crates will be downloaded from crates.io (needs internet).');
  }

  const toolsSource = join(src, 'tauri-tools-windows');
  if (tauriToolsCache && existsSync(toolsSource)) {
    log(`Restoring Tauri installer tools into ${tauriToolsCache}`);
    cpSync(toolsSource, tauriToolsCache, { recursive: true, force: false });
  }
  log('Offline dependencies ready. Build with: node scripts/build-release.mjs');
}

function online() {
  if (!existsSync(cargoConfigPath)) return log('Nothing to undo: cargo already uses crates.io.');
  if (!readFileSync(cargoConfigPath, 'utf8').startsWith(GENERATED_MARKER)) {
    fail(`${cargoConfigPath} was not created by this script; not removing it.`);
  }
  rmSync(cargoConfigPath);
  log('Removed .cargo/config.toml: cargo uses crates.io again.');
}

const [command, dir] = process.argv.slice(2);
switch (command) {
  case 'vendor':
    vendor(dir ?? join(repoRoot, 'dist', 'project-deps'));
    break;
  case 'restore':
    if (!dir) fail('Usage: node scripts/offline-deps.mjs restore <dir>');
    restore(dir);
    break;
  case 'online':
    online();
    break;
  default:
    console.log(readFileSync(fileURLToPath(import.meta.url), 'utf8').split('\n').slice(1, 12).join('\n'));
    process.exit(command ? 1 : 0);
}
